# headers and icon 
title: Ushai Chaudhuri
info: Scientist @ trddc
icon-pic: assets/img/mandu_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  
